In [1]:
# !pip install --user tensorflow_hub

In [2]:
# !pip install --user tensorflow_text

In [20]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-l-12-h-768-a-12/4"

In [12]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [13]:
test_text = ["nice movie indeed", "I love python programming"]
test_text_preprocessed = bert_preprocess_model(test_text) # creates a dictionary
test_text_preprocessed.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [15]:
test_text_preprocessed['input_mask']
# shape = (2,128) where 2 are the number of sentences adnd 128 is the max length of a sentence it can take and the 0s represent padding
# CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [16]:
test_text_preprocessed['input_word_ids']
# CLS-101, SEP-102

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [17]:
bert_model = hub.KerasLayer(encoder_url)

In [18]:
bert_results = bert_model(test_text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'encoder_outputs', 'sequence_output', 'default'])

In [23]:
bert_results['pooled_output']
# provides embedding for each word in a sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79188013, -0.21425518,  0.49721304, ...,  0.24413648,
        -0.4734776 ,  0.817745  ],
       [-0.91704917, -0.47915408, -0.7862837 , ..., -0.61722946,
        -0.7100538 ,  0.92182994]], dtype=float32)>

In [24]:
bert_results['sequence_output']
# 2 repesents the nummber of statements
# 128 represents the maximum permissible words in a sentence and the remaining are considered as padding
# padding does not always contain 0s but here the padding contains some values that represent the contextual embedding
# 768 is the feature vector for a complete word

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07285099,  0.08559467,  0.14486243, ..., -0.09696241,
          0.0874363 ,  0.07722519],
        [ 0.17854919, -0.19033203,  0.50342715, ..., -0.0592822 ,
          0.3274933 , -0.15570705],
        [ 0.18721128, -0.43419477, -0.48869985, ..., -0.15485501,
          0.00191848, -0.24450247],
        ...,
        [ 0.12076025,  0.12861368,  0.46467674, ...,  0.07385493,
          0.17424011,  0.16553491],
        [ 0.07972652, -0.01200814,  0.50237304, ...,  0.13797873,
          0.20989522,  0.00605734],
        [-0.07173504, -0.28292355,  0.59035784, ...,  0.4754444 ,
          0.16631758, -0.08909762]],

       [[-0.0785742 ,  0.3630514 , -0.2108549 , ..., -0.17174137,
          0.16314858,  0.6722267 ],
        [ 0.27904755,  0.4371235 , -0.3576929 , ..., -0.04426212,
          0.3837821 ,  0.5884484 ],
        [ 1.2049179 ,  1.072629  ,  0.48469776, ...,  0.2488006 ,
          0.40683615,  0.4054135 ],
        ...,

In [26]:
len(bert_results['encoder_outputs'])
# length is 12 as in the BERT base model, there are upto 12 encoders whereas in BERT large model, there are upto 24 encoders

12

In [31]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']
# here the result of the last encoder is considered to be the output of the model i.e. why the last encoder_output = sequence_output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>