In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
from keras.layers import Dense,InputLayer
from keras import Sequential

In [2]:
df = pd.read_csv("./datasets/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df.shape

(28, 3)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               28 non-null     int64
 1   affordibility     28 non-null     int64
 2   bought_insurance  28 non-null     int64
dtypes: int64(3)
memory usage: 804.0 bytes


In [5]:
# splitting of dataset
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(df[["age","affordibility"]],df["bought_insurance"],test_size=0.2,random_state=25)

In [6]:
xtrain.shape

(22, 2)

In [7]:
# scaling
xtrain_scaled = xtrain.copy()
xtrain_scaled['age'] /= 100

xtest_scaled = xtest.copy()
xtest_scaled['age'] /= 100

In [8]:
xtrain_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [ ]:
# creating neural network
model = Sequential([
    Dense(1,input_shape=(2,),activation="sigmoid",kernel_initializer="ones",bias_initializer="zeros"),
])

model.compile(
    optimizer='adam',
    loss="binary_crossentropy",
    metrics=['accuracy']
)

model.fit(xtrain_scaled,ytrain,epochs=5000)
# kernel_initializer -> weights
# bias_initializer -> bias

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 892ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9091 - loss: 0.5041
Epoch 3315/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9091 - loss: 0.5040
Epoch 3316/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9091 - loss: 0.5040
Epoch 3317/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9091 - loss: 0.5040
Epoch 3318/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9091 - loss: 0.5039
Epoch 3319/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9091 - loss: 0.5039
Epoch 3320/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9091 - loss: 0.5039
Epoch 3321/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9091 - loss: 0.5038
Epoch 3322/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9091 - loss: 0.5038
Epoch 3323/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9091 - loss: 0.5038
Epoch 3324/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9091 - loss: 0.5038
Epoch 3325/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms

In [27]:
# model.summary()

In [28]:
model.evaluate(xtest_scaled,ytest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 589ms/step - accuracy: 1.0000 - loss: 0.3550


[0.35497763752937317, 1.0]

In [29]:
ytest

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [30]:
model.predict(xtest_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [31]:
coef,intercept = model.get_weights()
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [32]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [33]:
def predicted_value(age,affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [34]:
xtest_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [35]:
predicted_value(0.61,1)

array([0.82949823], dtype=float32)

<h3 style="color: blue;">implementing gradient descent from scratch</h3>

In [1]:
# sigmoid function

In [2]:
def log_loss(y_true,y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new) + (1-y_true)*np.log(1-y_pred_new))

In [3]:
def gradient_descent(age,affordibility,y_true,epochs,loss_threshold):
    w1 = w2 = 1
    b = 0
    n = len(age)
    rate = 0.5
    for i in range(epochs):
        weighted_sum = w1*age + w2*affordibility + b
        y_pred = sigmoid(weighted_sum)
        loss = log_loss(y_true,y_pred)

        # convergence
        dj_dw1 = (1/n)*(np.dot(np.transpose(age),(y_pred - y_true)))
        dj_dw2 = (1/n)*(np.dot(np.transpose(affordibility),(y_pred - y_true)))
        dj_db = np.mean(y_pred - y_true)

        w1 = w1 - rate*dj_dw1
        w2 = w2 - rate*dj_dw2
        b = b - rate*dj_db
        print(f"Epoch:{i} w1:{w1} w2:{w2} b:{b} loss:{loss}")
        
        if loss <= loss_threshold:
            break
    return w1,w2,b

In [4]:
gradient_descent(xtrain_scaled["age"],xtrain_scaled['affordibility'],ytrain,1000,0.4631)

NameError: name 'xtrain_scaled' is not defined

In [40]:
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

# Part-13 Neural Network implementation

In [58]:
class myNN():
    def __init__(self):
        pass
    def fit(self,X,y,epochs,loss_threshold):
        self.w1,self.w2,self.bias = self.gradient_descent(X["age"],X["affordibility"],y,epochs,loss_threshold)
    def predict(self,X_test):
        weighted_sum = self.w1 * X_test["age"] + self.w2 * X_test["affordibility"] + self.bias
        return sigmoid(weighted_sum)
    def gradient_descent(self,age,affordibility,y_true,epochs,loss_threshold):
        w1 = w2 = 1
        b = 0
        n = len(age)
        rate = 0.5
        for i in range(epochs):
            weighted_sum = w1*age + w2*affordibility + b
            y_pred = sigmoid(weighted_sum)
            loss = log_loss(y_true,y_pred)

            # convergence
            dj_dw1 = (1/n)*(np.dot(np.transpose(age),(y_pred - y_true)))
            dj_dw2 = (1/n)*(np.dot(np.transpose(affordibility),(y_pred - y_true)))
            dj_db = np.mean(y_pred - y_true)

            w1 = w1 - rate*dj_dw1
            w2 = w2 - rate*dj_dw2
            b = b - rate*dj_db
            if i%50 == 0:
                print(f"Epoch:{i} w1:{w1} w2:{w2} b:{b} loss:{loss}")
        
            if loss <= loss_threshold:
                print(f"Epoch:{i} w1:{w1} w2:{w2} b:{b} loss:{loss}")
                break
        return w1,w2,b

In [59]:
customModel = myNN()
customModel.fit(xtrain_scaled,ytrain,500,0.4631)

Epoch:0 w1:0.974907633470177 w2:0.948348125394529 b:-0.11341867736368583 loss:0.7113403233723417
Epoch:50 w1:1.503319554173139 w2:1.108384790367645 b:-1.2319047301235464 loss:0.5675865113475955
Epoch:100 w1:2.200713131760032 w2:1.2941584023238903 b:-1.6607009122062801 loss:0.5390680417774752
Epoch:150 w1:2.8495727769689085 w2:1.3696895491572747 b:-1.986105845859897 loss:0.5176462164249294
Epoch:200 w1:3.443016970881804 w2:1.404221862446503 b:-2.2571369883752723 loss:0.5005011269691375
Epoch:250 w1:3.982450494649577 w2:1.423912732932123 b:-2.494377365971801 loss:0.48654089537617085
Epoch:300 w1:4.4721795220959155 w2:1.438787986553552 b:-2.7073878119223735 loss:0.47508146406327934
Epoch:350 w1:4.917245868007634 w2:1.4525660781176122 b:-2.901176333556766 loss:0.46561475306999006
Epoch:366 w1:5.051047623653049 w2:1.4569794548473887 b:-2.9596534546250037 loss:0.46293944095888917


In [60]:
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [61]:
customModel.predict(xtest_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

In [62]:
model.predict(xtest_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step


array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)