# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7],[1,2,32,90]],np.float32)

In [3]:
myarr[0,1]

6.0

In [6]:
myarr.dtype

dtype('float32')

In [7]:
myarr.shape

(2, 4)

In [8]:
 myarr[0,1] = 45

In [9]:
myarr

array([[ 3., 45., 37.,  7.],
       [ 1.,  2., 32., 90.]], dtype=float32)

# Array Creation:Conversion from other python structures

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({2,12,77})

array({2, 12, 77}, dtype=object)

In [19]:
np.array((1,0,29)).dtype

dtype('int32')

In [21]:
np.array({1:10,2:20,3:30})

array({1: 10, 2: 20, 3: 30}, dtype=object)

In [22]:
zeros = np.zeros((2,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(2,20)

In [19]:
rng

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
lspace = np.linspace(1,5,10)

In [21]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.95820216e-306, 3.33778734e-307, 1.11260280e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37960147e-306,
        1.33511562e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.02361614e-306, 1.78020848e-306, 1.78021527e-306,
        1.69119330e-306, 9.79101082e-307, 1.78020576e-306]])

In [27]:
emp_like = np.empty_like(myarr)

In [28]:
emp_like

array([[ 3., 45., 37.,  7.],
       [ 1.,  2., 32., 90.]], dtype=float32)

In [29]:
ide = np.identity(4)

In [30]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
ide.shape

(4, 4)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(33,3)

In [35]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [36]:
arr = arr.ravel()

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.shape

(99,)

# Axis in numpy

In [40]:
ar = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [41]:
ar.sum(axis=0)

array([ 6, 15,  8])

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
ar.flat

In [41]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.shape

(3, 3)

In [45]:
ar.nbytes

36

In [42]:
one = np.array([100,3,42.01,655,60])

In [43]:
one.argmax()

3

In [44]:
one.argmin()

1

In [45]:
ar.argmin()

8

In [46]:
ar.argmax()

6

In [47]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [48]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [53]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [54]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [55]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [59]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [60]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
ar.sum()

29

In [63]:
ar.max()

7

In [64]:
ar.min()

0

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
np.where(ar>1)

(array([0, 0, 1, 1, 1, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0], dtype=int64))

In [67]:
np.count_nonzero(ar)

8

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [69]:
ar[1,2] = 0
ar[2,0] = 0

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 1], dtype=int64))

In [71]:
import sys

In [72]:
py_ar = [4,55,0,12]

In [73]:
np_ar = np.array(py_ar)

In [80]:
sys.getsizeof(1) * len(py_ar)

112

In [75]:
np_ar.itemsize * np_ar.size

16

In [76]:
np_ar.tolist()

[4, 55, 0, 12]

# FDS core libraries

In [3]:
import numpy as np
myArr1 = np.array([1,2,34,5,67])
myArr2 = myArr1.view()

In [4]:
myArr2

array([ 1,  2, 34,  5, 67])

In [5]:
myArr2[3] = -1
myArr2

array([ 1,  2, 34, -1, 67])

In [6]:
myArr1

array([ 1,  2, 34, -1, 67])

In [7]:
myArr3 = myArr1.copy()
myArr3

array([ 1,  2, 34, -1, 67])

In [8]:
myArr3[2] = 10
myArr3

array([ 1,  2, 10, -1, 67])

In [9]:
myArr1

array([ 1,  2, 34, -1, 67])

In [10]:
# view created a pointer pointing to the same arr so if arr formed by view() is altered then the original arr will also change
# and the arr formed by copy() creates a new arr which is the copy of the previous arr

In [28]:
zeros = np.zeros((2,3),dtype=int)
# default dtype of zeros() and ones() is float64

In [24]:
num = np.arange(15,20,0.1)

In [25]:
num

array([15. , 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. ,
       16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1,
       17.2, 17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2,
       18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3,
       19.4, 19.5, 19.6, 19.7, 19.8, 19.9])

In [26]:
np.linspace(1.,4.,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [29]:
zeros[(0,2)]

0

In [30]:
num[1:14]

array([15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1,
       16.2, 16.3])

# mathematical,logarithmic,statistical,exponential,trigonometrical operations

In [41]:
myarr13 = np.array([1.,2.2,13.6,26.89,14.11])

In [42]:
myarr13.min()

1.0

In [52]:
np.min(myarr13)

1.0

In [43]:
myarr13.max()

26.89

In [50]:
np.max(myarr13)

26.89

In [44]:
myarr13.mean()

11.559999999999999

In [45]:
np.mean(myarr13)

11.559999999999999

In [53]:
np.median(myarr13)

13.6

In [56]:
np.var(myarr13)

88.95924

In [61]:
np.cov(myarr13) 
#covariance

array(111.19905)

In [62]:
np.std(myarr13)

9.431820608981068

In [64]:
np.abs(myarr13)

array([ 1.  ,  2.2 , 13.6 , 26.89, 14.11])

In [65]:
np.sort(myarr13)

array([ 1.  ,  2.2 , 13.6 , 14.11, 26.89])

In [68]:
np.sin(myarr13)

array([0.84147098, 0.8084964 , 0.85916181, 0.98266619, 0.999631  ])

In [69]:
np.cos(myarr13)

array([ 0.54030231, -0.58850112,  0.51170399, -0.18538383,  0.0271636 ])

In [71]:
np.tan(myarr13)

array([ 1.55740772, -1.37382306,  1.67902113, -5.30071155, 36.80038794])

In [73]:
np.log(myarr13)
# base e

array([0.        , 0.78845736, 2.61006979, 3.29175447, 2.64688377])

In [74]:
np.log10(myarr13)
# base 10

array([0.        , 0.34242268, 1.13353891, 1.4295908 , 1.14952701])

In [75]:
np.exp(myarr13)

array([2.71828183e+00, 9.02501350e+00, 8.06129759e+05, 4.76626976e+11,
       1.34244079e+06])

In [76]:
np.prod(myarr13)

11352.183568

In [77]:
np.sum(myarr13)

57.8

In [82]:
np.power(myarr13,2)

array([  1.    ,   4.84  , 184.96  , 723.0721, 199.0921])

In [83]:
np.sqrt(myarr13)

array([1.        , 1.4832397 , 3.68781778, 5.18555686, 3.75632799])

In [86]:
myarr13[0] = 10
myarr13

array([10.  ,  2.2 , 13.6 , 26.89, 14.11])

In [89]:
myarr13.size

5

In [91]:
myarr13.dtype

dtype('float64')

In [118]:
myarr14 = np.arange(10,20)
myarr14

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
myarr14 + 12

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [96]:
myarr14 - 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
myarr14 * 2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [98]:
myarr14 / 7

array([1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ,
       2.14285714, 2.28571429, 2.42857143, 2.57142857, 2.71428571])

In [99]:
myarr14 // 5

array([2, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int32)

In [100]:
myarr14 % 13

array([10, 11, 12,  0,  1,  2,  3,  4,  5,  6], dtype=int32)

In [106]:
myarr15 = np.arange(90,99)
myarr16 = np.arange(1,10)
myarr15,myarr16

(array([90, 91, 92, 93, 94, 95, 96, 97, 98]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [109]:
myarr15>myarr16

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [111]:
np.matrix('1, 2, 3, 4;5, 6, 7, 8;9, 10, 11, 12')

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [114]:
myarr15.reshape((3,3))

array([[90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [120]:
np.reshape(myarr14,(5,2))

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])