In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
iris = sns.load_dataset('iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
# iris.to_excel("iris.xlsx")

In [4]:
x = iris.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y = iris.iloc[:,4].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
# Encoding species to numbers

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# if the data is not in the same scale then we use feature
# scaling

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [10]:
# logistic Regression algorithm
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred = logmodel.predict(x_test)

In [12]:
y_pred

array([1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1,
       1, 2, 0, 2, 0, 2, 2, 1])

In [13]:
y_test

array([1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1,
       1, 2, 0, 2, 0, 2, 2, 1])

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)
# first row/column is for setosa then from both rows and
# columns,there will be 5 setosas.
# diagonal numbers are true for both scenarios

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]], dtype=int64)

In [15]:
# accuracy = sum of diagonal/total sum
27/30

0.9

In [16]:
# k-nearest neighbor algorithm
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
# p=2 is for euclidean distance and 1 is for manhatten distance.
# 'minkowski' is the name of the scientist who discovered these 2 distances.
# n_neighbors=5 means that it will choose among the classification of 5 nearest neighbors.
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [17]:
y_pred = classifier_knn.predict(x_test)
y_pred

array([1, 1, 2, 0, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1,
       1, 2, 0, 2, 0, 2, 2, 1])

In [18]:
y_test

array([1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1,
       1, 2, 0, 2, 0, 2, 2, 1])

In [19]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]], dtype=int64)

In [20]:
# accuracy
28/30

0.9333333333333333

In [21]:
# naiive bayes algorithm
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [22]:
y_pred = classifier_nb.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1,
       1, 2, 0, 2, 0, 1, 2, 1])

In [23]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  9]], dtype=int64)

In [24]:
# accuracy
26/30

0.8666666666666667

In [25]:
# support vector machine algorithm
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [26]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [27]:
confusion_matrix(y_pred,y_test)
# all the flowers are of first type

array([[ 2,  9, 10],
       [ 0,  0,  0],
       [ 8,  1,  0]], dtype=int64)

In [28]:
# accuracy
5/30

0.16666666666666666

In [29]:
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [30]:
y_pred = classifier_svm_linear.predict(x_test)

In [31]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]], dtype=int64)

In [32]:
# accuracy
30/30

1.0

In [33]:
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [34]:
y_pred = classifier_svm_rbf.predict(x_test)

In [35]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]], dtype=int64)

In [36]:
# accuracy
28/30

0.9333333333333333

In [37]:
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [38]:
y_pred = classifier_svm_poly.predict(x_test)

In [39]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]], dtype=int64)

In [40]:
# accuracy
28/30

0.9333333333333333

In [41]:
# decision tree
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)
# entropy is used here to represent impurity in the data

DecisionTreeClassifier(criterion='entropy')

In [42]:
y_pred = classifier_dt.predict(x_test)

In [43]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [44]:
# accuracy
26/30

0.8666666666666667

In [45]:
from sklearn.ensemble import RandomForestClassifier
# ensemble learning means one model works in another model
# like random forest includes decision tree during 
# its working
classifier_rf = RandomForestClassifier(n_estimators=3,criterion='entropy')
# n_estimator -> how many times to run the decision tree
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [46]:
y_pred = classifier_rf.predict(x_test)

In [47]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  8]], dtype=int64)

In [48]:
# accuracy -> better than decision tree
27/30

0.9

In [49]:
# we conclude that we get a good accuracy of our model by using svm(kernel='linear')